<?php
if( function_exists('acf_add_local_field_group') ) {
    // Global (Posts and Pages)
    acf_add_local_field_group(array(
        'key' => 'global_group',
        'title' => 'Banner (Global Posts/Pages)',
        'fields' => array(
            array(
                'key' => 'global_banner_title',
                'label' => 'Title',
                'name' => 'global_title',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'global_banner_title_sub',
                        'label' => 'Sub Text (optional)',
                        'name' => 'sub',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'global_banner_title_main',
                        'label' => 'Main Text',
                        'name' => 'main',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '!=',
                    'value' => 'templates/homepage.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
    // Homepage Template
    acf_add_local_field_group(array(
        'key' => 'hp_group',
        'title' => 'Homepage',
        'fields' => array(
            // TopFold
            array(
                'key' => 'hp_topfold',
                'label' => 'Topfold Banner',
                'name' => 'topfold_banner',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'hp_topfold_banner_text',
                        'label' => 'Banner Text',
                        'name' => 'banner_text',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '', 
                    ),
                    array(
                        'key' => 'hp_topfold_cta',
                        'label' => 'Topfold Call to Action Buttons',
                        'name' => 'topfold_cta',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'hp_topfold_cta_buy_now',
                                'label' => 'Buy Now Link',
                                'name' => 'buy_now_link',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '', 
                            ),
                            array(
                                'key' => 'hp_topfold_cta_right',
                                'label' => 'Phone Number',
                                'name' => 'topfold_phone_number',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '', 
                            ),
                        ),
                    ),
                ),
            ),
            // Product Section
            array(
                'key' => 'hp_products',
                'label' => 'Products Section',
                'name' => 'product_section',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'hp_products_title',
                        'label' => 'Product Title',
                        'name' => 'product_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '', 
                    ),
                    array(
                        'key' => 'hp_products_slider',
                        'label' => 'Products Slider',
                        'name' => 'product_slider',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'row',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'hp_product_image',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'hp_product_name',
                                'label' => 'Product Name',
                                'name' => 'name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'hp_product_subtitle',
                                'label' => 'Product Sub Name',
                                'name' => 'subname',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'hp_product_buy_link',
                                'label' => 'Buy Link',
                                'name' => 'buy_link',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
            ),
            // About the Company
            array(
                'key' => 'hp_about_company',
                'label' => 'About the Company',
                'name' => 'about_company',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'hp_about_company_image',
                        'label' => 'Image',
                        'name' => 'image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'hp_about_company_content',
                        'label' => 'About The Company Content',
                        'name' => 'about_company_content',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'hp_about_company_header',
                                'label' => 'Header',
                                'name' => 'about_header',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'hp_about_company_subheader',
                                'label' => 'Sub Header',
                                'name' => 'about_subheader',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'hp_about_company_paragraph',
                                'label' => 'Content',
                                'name' => 'about_content',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'hp_about_company_readmore_link',
                                'label' => 'Read More Link',
                                'name' => 'about_read_more',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
            ),
            // Founders
            array(
                'key' => 'hp_founders',
                'label' => 'Founder Section',
                'name' => 'founder_section',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'hp_founders_header',
                        'label' => 'Founder Section header',
                        'name' => 'founder_header',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '', 
                    ),
                    array(
                        'key' => 'hp_founders_slider',
                        'label' => 'Founders Slider',
                        'name' => 'founders_slider',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'row',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'hp_founder_image',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'hp_founder_name',
                                'label' => 'Founder Name',
                                'name' => 'name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'hp_founder_title',
                                'label' => 'Founder title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'hp_founder',
                                'label' => 'Founder Position',
                                'name' => 'position',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
            ),
            // Events
            array(
                'key' => 'hp_events',
                'label' => 'Events Section',
                'name' => 'events_section',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'hp_events_header',
                        'label' => 'Events Section Header',
                        'name' => 'events_header',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '', 
                    ),
                    array(
                        'key' => 'hp_events_slider',
                        'label' => 'Events Slider',
                        'name' => 'events_slider',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'row',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'hp_sliders_events_image',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'hp_sliders_events_title',
                                'label' => 'Events title',
                                'name' => 'event_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '', 
                            ),
                            array(
                                'key' => 'hp_events_slider_date',
                                'label' => 'Events Date',
                                'name' => 'events_date',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'hp_event_date_month',
                                        'label' => 'Events Month',
                                        'name' => 'event_month',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '', 
                                    ),
                                    array(
                                        'key' => 'hp_event_date_day',
                                        'label' => 'Events Day',
                                        'name' => 'event_day',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '', 
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'hp_events_read_more',
                        'label' => 'Read More Link',
                        'name' => 'events_read_more',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '', 
                    ),
                ),
            ),
            // Get In Touch
            array(
                'key' => 'hp_contact',
                'label' => 'Contact Us Section',
                'name' => 'contact_section',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'hp_contact_header',
                        'label' => 'Contact Us Header',
                        'name' => 'contact_header',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'hp_contact_subheader',
                        'label' => 'Contact Us SubHeader',
                        'name' => 'contact_subheader',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'hp_contact_info',
                        'label' => 'Contact Us Information',
                        'name' => 'contact_information',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'hp_contact_info_email',
                                'label' => 'Email',
                                'name' => 'contact_email',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'hp_contact_info_location',
                                'label' => 'Location',
                                'name' => 'contact_location',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'hp_contact_info_phone',
                                'label' => 'Phone',
                                'name' => 'contact_phone',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array(    
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '==',
                    'value' => 'templates/homepage.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));
    // About Us Template
    acf_add_local_field_group(array(
        'key' => 'about_group',
        'title' => 'About Us',
        'fields' => array(
            array(
                'key' => 'content_sections',
                'label' => 'Content Sections',
                'name' => 'content_section',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'about_section_1',
                        'label' => 'Section 1',
                        'name' => 'about_section_1',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'section_1_image',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'section_1_content',
                                'label' => 'Section 1 Content',
                                'name' => 'content_text',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'row',
                                'button_label' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'section_content_title',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'section_content_message',
                                        'label' => 'Content',
                                        'name' => 'message',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
        
                        ),
                    ),
                    array(
                        'key' => 'about_section_2',
                        'label' => 'Section 2',
                        'name' => 'about_section_2',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'section_2_image',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'section_2_content',
                                'label' => 'Section 2 Content',
                                'name' => 'content_text',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'row',
                                'button_label' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'section_content_title',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'section_content_message',
                                        'label' => 'Content',
                                        'name' => 'message',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
        
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'mission_vision_group',
                'label' => 'Mission and Vision',
                'name' => 'mission_vision',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'Mission',
                        'label' => 'Mission Content',
                        'name' => 'mission',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'mission_content_title',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'mission_content_message',
                                'label' => 'Content',
                                'name' => 'message',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'Vision',
                        'label' => 'Vision Content',
                        'name' => 'vision',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'vision_content_title',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'vision_content_message',
                                'label' => 'Content',
                                'name' => 'message',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array(    
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '==',
                    'value' => 'templates/about.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));
    // Contact Us Template
    acf_add_local_field_group(array(
        'key' => 'contact_group',
        'title' => 'Contact Us',
        'fields' => array(
            // Get In Touch
            array(
                'key' => 'contact_us_section',
                'label' => 'Contact Us Section',
                'name' => 'contact_us_section',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'cu_contact_header',
                        'label' => 'Contact Us Header',
                        'name' => 'contact_us_header',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'cu_contact_subheader',
                        'label' => 'Contact Us SubHeader',
                        'name' => 'contact_us_subheader',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'cu_contact_info',
                        'label' => 'Contact Us Information',
                        'name' => 'contact_us_information',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'cu_contact_info_email',
                                'label' => 'Email',
                                'name' => 'contact_us_email',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'cu_contact_info_location',
                                'label' => 'Location',
                                'name' => 'contact_us_location',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'cu_contact_info_phone',
                                'label' => 'Phone',
                                'name' => 'contact_us_phone',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array(    
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '==',
                    'value' => 'templates/contact.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));


    // // Privacy Policy Template
    // acf_add_local_field_group(array(
    //     'key' => 'group_627201725b3d1',
    //     'title' => 'Privacy Policy',
    //     'fields' => array(
    //         array(
    //             'key' => 'field_62720528b405a',
    //             'label' => 'Title',
    //             'name' => 'title',
    //             'type' => 'text',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'default_value' => '',
    //             'placeholder' => '',
    //             'prepend' => '',
    //             'append' => '',
    //             'maxlength' => '',
    //         ),
    //         array(
    //             'key' => 'field_6272136437cf2',
    //             'label' => 'Content',
    //             'name' => 'content',
    //             'type' => 'wysiwyg',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'default_value' => '',
    //             'tabs' => 'all',
    //             'toolbar' => 'basic',
    //             'media_upload' => 0,
    //             'delay' => 0,
    //         ),
    //         array(
    //             'key' => 'field_627204beb4057',
    //             'label' => 'Policies',
    //             'name' => 'list',
    //             'type' => 'repeater',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'collapsed' => 'field_627204d8b4058',
    //             'min' => 0,
    //             'max' => 0,
    //             'layout' => 'row',
    //             'button_label' => 'Add Policy',
    //             'sub_fields' => array(
    //                 array(
    //                     'key' => 'field_627204d8b4058',
    //                     'label' => 'Heading',
    //                     'name' => 'heading',
    //                     'type' => 'text',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'prepend' => '',
    //                     'append' => '',
    //                     'maxlength' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_62720519b4059',
    //                     'label' => 'Content',
    //                     'name' => 'content',
    //                     'type' => 'wysiwyg',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'tabs' => 'all',
    //                     'toolbar' => 'basic',
    //                     'media_upload' => 0,
    //                     'delay' => 0,
    //                 ),
    //             ),
    //         ),
    //     ),
    //     'location' => array(
    //         array(
    //             array(
    //                 'param' => 'post_template',
    //                 'operator' => '==',
    //                 'value' => 'templates/privacy-policy.php',
    //             ),
    //         ),
    //     ),
    //     'menu_order' => 0,
    //     'position' => 'normal',
    //     'style' => 'default',
    //     'label_placement' => 'top',
    //     'instruction_placement' => 'label',
    //     'hide_on_screen' => '',
    //     'active' => 1,
    //     'description' => '',
    // ));
    
    // // FAQ Template
    // acf_add_local_field_group(array(
    //     'key' => 'group_630fe8bb504f0',
    //     'title' => 'FAQ',
    //     'fields' => array(
    //         array(
    //             'key' => 'field_631038ce604ee',
    //             'label' => 'Title',
    //             'name' => 'title',
    //             'type' => 'text',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'default_value' => '',
    //             'placeholder' => '',
    //             'prepend' => '',
    //             'append' => '',
    //             'maxlength' => '',
    //         ),
    //         array(
    //             'key' => 'field_630fe8dabcf6a',
    //             'label' => 'Questions',
    //             'name' => 'questions',
    //             'type' => 'repeater',
    //             'instructions' => '',
    //             'required' => 0,
    //             'conditional_logic' => 0,
    //             'wrapper' => array(
    //                 'width' => '',
    //                 'class' => '',
    //                 'id' => '',
    //             ),
    //             'collapsed' => 'field_6310414f58afd',
    //             'min' => 0,
    //             'max' => 0,
    //             'layout' => 'block',
    //             'button_label' => 'Add Question',
    //             'sub_fields' => array(
    //                 array(
    //                     'key' => 'field_63103906604f0',
    //                     'label' => 'Type',
    //                     'name' => 'type',
    //                     'type' => 'select',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'choices' => array(
    //                         'Single Content' => 'Single Content',
    //                         'In Groups' => 'In Groups',
    //                     ),
    //                     'default_value' => array(
    //                         0 => 'a',
    //                         1 => 'b',
    //                     ),
    //                     'allow_null' => 0,
    //                     'multiple' => 0,
    //                     'ui' => 0,
    //                     'ajax' => 0,
    //                     'return_format' => 'value',
    //                     'placeholder' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_6310414f58afd',
    //                     'label' => 'Heading',
    //                     'name' => 'heading',
    //                     'type' => 'text',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => 0,
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'placeholder' => '',
    //                     'prepend' => '',
    //                     'append' => '',
    //                     'maxlength' => '',
    //                 ),
    //                 array(
    //                     'key' => 'field_631039aa604f1',
    //                     'label' => 'Content',
    //                     'name' => 'content',
    //                     'type' => 'wysiwyg',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => array(
    //                         array(
    //                             array(
    //                                 'field' => 'field_63103906604f0',
    //                                 'operator' => '==',
    //                                 'value' => 'Single Content',
    //                             ),
    //                         ),
    //                     ),
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'default_value' => '',
    //                     'tabs' => 'text',
    //                     'toolbar' => 'basic',
    //                     'media_upload' => 1,
    //                     'delay' => 0,
    //                 ),
    //                 array(
    //                     'key' => 'field_63103ee2604f2',
    //                     'label' => 'Groups',
    //                     'name' => 'groups',
    //                     'type' => 'repeater',
    //                     'instructions' => '',
    //                     'required' => 0,
    //                     'conditional_logic' => array(
    //                         array(
    //                             array(
    //                                 'field' => 'field_63103906604f0',
    //                                 'operator' => '==',
    //                                 'value' => 'In Groups',
    //                             ),
    //                         ),
    //                     ),
    //                     'wrapper' => array(
    //                         'width' => '',
    //                         'class' => '',
    //                         'id' => '',
    //                     ),
    //                     'collapsed' => 'field_63103f19604f3',
    //                     'min' => 1,
    //                     'max' => 0,
    //                     'layout' => 'block',
    //                     'button_label' => 'Add Group',
    //                     'sub_fields' => array(
    //                         array(
    //                             'key' => 'field_63103f19604f3',
    //                             'label' => 'Heading',
    //                             'name' => 'sub_heading',
    //                             'type' => 'text',
    //                             'instructions' => '',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
    //                             'default_value' => '',
    //                             'placeholder' => '',
    //                             'prepend' => '',
    //                             'append' => '',
    //                             'maxlength' => '',
    //                         ),
    //                         array(
    //                             'key' => 'field_63103f1f604f4',
    //                             'label' => 'Content',
    //                             'name' => 'content',
    //                             'type' => 'wysiwyg',
    //                             'instructions' => '',
    //                             'required' => 0,
    //                             'conditional_logic' => 0,
    //                             'wrapper' => array(
    //                                 'width' => '',
    //                                 'class' => '',
    //                                 'id' => '',
    //                             ),
    //                             'default_value' => '',
    //                             'tabs' => 'text',
    //                             'toolbar' => 'basic',
    //                             'media_upload' => 1,
    //                             'delay' => 0,
    //                         ),
    //                     ),
    //                 ),
    //             ),
    //         ),
    //     ),
    //     'location' => array(
    //         array(
    //             array(
    //                 'param' => 'page_template',
    //                 'operator' => '==',
    //                 'value' => 'templates/faq.php',
    //             ),
    //         ),
    //     ),
    //     'menu_order' => 0,
    //     'position' => 'normal',
    //     'style' => 'default',
    //     'label_placement' => 'top',
    //     'instruction_placement' => 'label',
    //     'hide_on_screen' => '',
    //     'active' => 1,
    //     'description' => '',
    // ));
}